[package]
name = "kxc"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
chrono = "0.4.41"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
aes = "0.8"
ctr = "0.9"
hex = "0.4"
anyhow = "1.0.98"
